Feature/1 profile
mahlenko/iOS-FakeNFT-StarterProject-Public pull request #17
Opened 2023-06-09 22:28 UTC by DemidenGo

- Архитектура MVVM, вёрстка кодом
- [Ссылка на таск-трекер с задачами](https://trello.com/b/5CFGRhC1/дипломный-проект-ios-nft)
- Приложенный текстовый документ .md: [FakeNFT](https://github.com/DemidenGo/FakeNFT/tree/feature/1_profile)
- Первоначальная оценка времени выполнения задач: [FakeNFT](https://github.com/DemidenGo/FakeNFT/tree/feature/1_profile)
- Реальное время, потраченное на решении каждой задачи: [FakeNFT](https://github.com/DemidenGo/FakeNFT/tree/feature/1_profile)

2023-06-12 06:45 UTC, IBDesignable commented
@DemidenGo Не вижу кросс ревью от коллег. Нужно собрать апрув

2023-06-12 08:26 UTC, IBDesignable requested changes
Свой модуль лучше переложить в Scenes (экраны)
<img width="271" alt="Снимок экрана 2023-06-12 в 11 19 34" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/d8183f69-6f8f-43a2-90f8-1e56cb9e29ee">


Хорошо бы добавить валидацию ссылки, которая вставляется в данных пользователя и добавить кликабельность, если это ссылка. 
<img width="200" alt="Снимок экрана 2023-06-12 в 11 20 26" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/a062aff5-95de-49cb-bd3d-43a8e4951407"><img width="200" alt="Снимок экрана 2023-06-12 в 11 21 08" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/3b3de7c1-2693-4e6f-9277-376c2a48ceab">

Данные пользователя не сохраняются, если экран смахнуть. Тут может вызвать недоумение почему сохранение происходит только по крестику. Здесь крестик и свайп вниз равнозначные по UX методы – поэтому сохранение и на dismiss хорошо было бы сделать. Либо же иногда делают алерт с подтверждением действия: уйти без сохранения / с сохранением, чтобы у пользователя была альтернатива. 
<img width="458" alt="Снимок экрана 2023-06-12 в 11 22 06" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/f048be51-fd75-4ede-bb32-b61c86d9af6f">

на этом экране есть кнопки лайка, но они ничего не делают. Здесь расхождение с ТЗ и дизайном, и софтскильно было бы прийти и спросить заказчика - а как правильно. Оставлять некликабельные кнопки – выглядит ошибкой (я тыкаю, а ничего не происходит)
Как я выяснила – в макетах забыли убрать, ты можешь уточнить это у Наставника и решить как поступить с ними: убрать с экрана либо дореализовать запросы на лайк.

<img width="458" alt="Снимок экрана 2023-06-12 в 11 25 21" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/9bbf4ba8-4314-413a-96ee-27c1002dbda3">

2023-06-12 08:26 UTC, IBDesignable commented on FakeNFTUITests/ProfileUITests.swift
> +    }
раз уж ты единственный кто успел сделать тесты: удали еще и example тесты, которые не нужны :)

2023-06-12 20:28 UTC, IBDesignable commented
Есть что доправить, фиксим и мерджим ветку в основную (дожидаясь готовности команды).
[Юрий Демиденко - Ревью диплома.pdf](https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/files/11728046/-.pdf)

2023-06-13 11:20 UTC, mp3moto approved these changes
Предлагаю сделать мердж с develop-веткой Махленко, далее в в отдельной ветке переиспользовать уже готовые компоненты

2023-06-13 11:20 UTC, mp3moto commented on FakeNFT/Profile/View/MyNFTTableViewCell.swift
> +        return fullString
после мерджа можно будет воспользоваться готовым RatingView. У всех одинаково будет

2023-06-14 13:33 UTC, DemidenGo commented on FakeNFT/Profile/Model/ProfileNetworkClient.swift
> +        self.session = session
Стандартным клиентом было невозможно сделать PUT запрос на обновление профиля, там вообще не было httpBody, только query. Сделал свой клиент, сейчас использую только его и для профиля и для экранов НФТ, то есть сейчас у меня только один клиент будет.

2023-06-14 19:23 UTC, DemidenGo commented on FakeNFT/Profile/View/EditProfileViewController.swift
> +    private lazy var websiteStackView = makeStackView(with: [websiteLabel, websiteTextVField])
Не совсем понял, как это реализовать. Можно немного подсказать?) В этом контроллере мне нужен доступ ко всем текстфилдам, чтобы забирать оттуда введённый текст. Также, мне нужно текстфилду устанавливать делегата. Также, мне нужен доступ к текстфилдам для задания констрейнтов. Попробовал сделать внешний StackViewMaker - как-то сложно получается...

2023-06-15 03:52 UTC, mp3moto commented on FakeNFT/Profile/View/EditProfileViewController.swift
> +    private lazy var websiteStackView = makeStackView(with: [websiteLabel, websiteTextVField])
Скорее всего, имелось в виду что можно создать подкласс для UITextView, который принимает доп. параметры, такие как текст надписи на ним. А выдает UIView с нарисованными элементами, а через свойства или методы класса можешь получить введенные значения.

2023-06-15 23:30 UTC, merged