Cross-review
mahlenko/iOS-FakeNFT-StarterProject-Public pull request #2
Opened 2023-05-24 22:25 UTC by mahlenko

2023-05-25 05:02 UTC, mp3moto commented on FakeNFT/Scenes /Cart/OrderDetails/OrderDetailsTableViewCell.swift
> +        self.itemIndex = itemIndex
self.itemIndex = itemIndex
Это точно нужно? Выглядит как-то не очень

2023-05-25 06:47 UTC, mahlenko commented on FakeNFT/Scenes /Cart/CartViewController.swift
>          let tableView = tableViewController.tableView!
Тут OrderDetailsTableViewController наследуется от UITableViewController, а у него требуется tableView, также unwrap. Тут нет смысла скорее от проверки. И возвращается у меня **TableViewController

2023-05-25 07:29 UTC, mahlenko commented on FakeNFT/Scenes /Cart/OrderDetails/OrderDetailsTableViewCell.swift
>      }()
На самом деле без разницы. Обычно я не создаю переменных, если они после не используются. Или без них получается слишком длинная строка :) Единственное тут можно обойтись без "{..}"

2023-05-25 07:31 UTC, mahlenko commented on FakeNFT/Scenes /Cart/OrderDetails/OrderDetailsTableViewCell.swift
> +        self.itemIndex = itemIndex
Ага :) так проще потом искать нужный элемент в массиве, а точнее не нужно перебирать весь массив элементов. Не то что бы очень важно, но упрощает последующую работу. Спасибо

2023-05-25 07:33 UTC, mahlenko commented on FakeNFT/Scenes /Cart/OrderDetails/OrderDetailsTableViewCell.swift
> +        imageAsset.register(imageDark, with: .init(userInterfaceStyle: .dark))
Спасибо, тут я что-то тупанул) но попробовал сделать это кодом, раньше не знал про imageAsset

2023-05-25 07:35 UTC, mp3moto commented on FakeNFT/Scenes /Cart/CartViewController.swift
>          let tableView = tableViewController.tableView!
Говорят, ружьё на стене тоже стреляет

2023-05-26 10:19 UTC, IBDesignable commented
Привет, @mahlenko!

Мне не хватает информации о работе: 

- выбранная командой архитектура и способ верстки
- декомпозиция эпика (ссылка на таск-трекер)
- декомпозиция эпика (приложенный текстовый документ .md)
- первоначальная оценка времени выполнения задач
- реальное время, потраченное на решении каждой задачи

Все необходимое прямым текстом или ссылками на информацию на доске нужно добавить в шапку ПР, вот сюда:
<img width="845" alt="Снимок экрана 2023-05-26 в 13 18 27" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/4b07046d-2deb-4c68-966a-6097c602b73c">

2023-05-26 11:02 UTC, mahlenko commented
@IBDesignable Привет, добавил

2023-05-27 09:59 UTC, IBDesignable commented
@mahlenko закинь пожалуйста обратно на платформу

2023-05-27 10:10 UTC, mahlenko commented
@IBDesignable закинул. Я сделал изменения в оригинальном (что предоставлялся нам сразу) NetworkClient и NetworkRequest.

У нас в корзине и для того, чтобы удалить или добавить в корзину NFT нужно отправить запрос к API на изменение заказа.

NetworkRequest по-умолчанию принимает только строки как ключ и значение. Но в корзине у нас **массив nfts:["1", "2", "3"]**, что с реализаций по-умолчанию невозможно.

Ребята из команды предложили обновить клиент через расширения. Но через расширения это получится по большому счету переписать процентов 80 оригинального клиента. В чем я не вижу смысла. 

Предложил команде просто немного изменить текущий клиент и запрос в 4 строки. И не писать каждому свою реализацию через расширения или просто нового клиента. Добавил отправку заголовка content-type: application/json + возможность указать в запрос httpBody и использование этого уже в клиенте.

2023-05-27 10:20 UTC, mahlenko commented
@IBDesignable MVVM я пока не использовал, не изучил еще как это правильно реализовывать. Думал оставить это на позже. Сделал пока как вижу/знаю :) Соберу полностью все экраны и уже переделаю под MVVM. Просили отправить на кросс-ревью в том виде, что есть - отправил.

2023-05-27 14:01 UTC, IBDesignable requested changes

2023-05-27 18:34 UTC, mahlenko commented on FakeNFT/DesignSystem/Components/NFT/PreviewImageComponent.swift
> +        }
2) `image = nil`
под изображением, немного анимирован фон. Пока изображение не загружено (изображения нет), видна эта анимация. Если новое изображение будет грузится долго, будет видна какая-то работа, если не убирать изображение, не понятно будет загрузка нового идет или нет.

Мне такой вариант взаимодействия показался лучше.

2023-05-27 18:38 UTC, mahlenko commented on FakeNFT/Models/Network/NftNetworkModel.swift
> +            (result: Result<NftNetworkModel, Error>) -> Void in
Окей. 
IDE сам его подставляет, я и не заморачивался :)

2023-05-27 18:46 UTC, mahlenko commented on FakeNFT/Scenes /Cart/CartViewController.swift
> +        UISelectionFeedbackGenerator().selectionChanged()
1) про childVC не знал, узнаю/почитаю. *Controller используются в оригинальном репозитории, решил следовать им.

Надо с этим разобраться еще, но мне кажется тейбл контроллер удобно использовать, вынес отдельно в файл, и не засоряешь контроллер. Хотя наверное есть и другие способы: паттерны

2) также не знал, попробую разобраться

2023-05-27 18:58 UTC, mahlenko commented on FakeNFT/Scenes /Cart/DeleteItemViewController.swift
> +    var delegate: UpdateCartViewProtocol?
Я правильно понимаю, что нужно `weak var delegate: UpdateCartViewProtocol?` но если weak то не протокол нужно использовать, а класс который реализует протокол?

2023-05-27 19:04 UTC, mahlenko commented on FakeNFT/Scenes /Cart/OrderDetails/OrderDetailsTableViewController.swift
> +
в общем-то, я с этой же мыслью и делал reloadData, что большого количества тут вряд ли будет

2023-05-27 19:05 UTC, mahlenko commented on FakeNFT/Scenes /Pay/PayStatusViewController.swift
> +    private lazy var imageView: UIImageView = { [self] in
похоже случайно, спасибо. Уже убрал, до чтения ревью

2023-05-27 21:10 UTC, mahlenko commented on FakeNFT/Scenes /Pay/PayViewController.swift
> +    }()
По поводу 1 пункта не понял, в макете она синяя. По поводу второго понял, был у меня вопрос пока делал, а как ссылку показывать в тексте. Просто по макету дизайна, там 2 элемента, я собирал также

2023-05-28 09:03 UTC, IBDesignable commented on FakeNFT/DesignSystem/Components/NFT/PreviewImageComponent.swift
> +        }
ок, оставляй) спасибо

2023-05-28 09:04 UTC, IBDesignable commented on FakeNFT/Models/Network/NftNetworkModel.swift
> +            (result: Result<NftNetworkModel, Error>) -> Void in
не настало еще время когда можно доверять Xcode)

2023-06-04 21:16 UTC, merged

2023-06-16 10:43 UTC, mahlenko commented
@IBDesignable Привет, у нас печально со сдачей 20 спринта, мы дожидались все эпики и планировали отправить сразу собранное приложение. Поэтому на столько затянулось. С 1 эпиком сейчас не известно что, решил объединять вчера за коллегу с дев веткой :)

В этом пул реквесте по-большому счету конечный результат, после мержа, были небольшие доработки, если не ошибаюсь по WebViewService. И что-то еще. Но 99.9% работы находится тут.

2023-06-18 14:53 UTC, IBDesignable commented
[Сергей Махленко - Ревью диплома.pdf](https://github@mahlenko com/mahlenko/iOS-FakeNFT-StarterProject-Public/files/11781830/-.pdf)

@mahlenko продолжай работу: мерджить можно. Исправить следует один баг с навигацией, остальное можно проигнорировать. 
Комментариев по коду к сожалению уже не будет, так как код вмерджен :(

2023-06-18 17:47 UTC, mahlenko commented
> [Сергей Махленко - Ревью диплома.pdf](https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/files/11781835/-.pdf)
> 
> @mahlenko продолжай работу: мерджить можно. Исправить следует один баг с навигацией, остальное можно проигнорировать.
> 
> Комментариев по коду к сожалению уже не будет, так как код вмерджен :(
> 
> Следующий шаг: смердженный код с остальными готовыми ветками (дождаться команду). В редми от каждого видео-демонстрацию своего эпика

Спасибо за ревью. PDF файл не мой) имя мое, но тут про профиль все. У меня Cart. )

2023-06-19 05:44 UTC, IBDesignable commented
:( моя вина, сейчас еще раз пересмотрю работу

2023-06-19 06:34 UTC, IBDesignable commented
[Сергей Махленко - Корзина - Ревью диплома.pdf](https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/files/11784976/-.-.pdf)


В работе есть критические замечания по базовому варианту, их нужно доправить самостоятельно.
Работа допущена до мерджа с основной веткой. Мердж должен происходить вместе со всей группой

Возвращай работу с вмердженными эпиками. Нужно будет приложить скринкаст с демонстрацией своего эпика на симуляторе. 
Желательно оформить эту часть работы тоже в PR.

2023-06-19 06:38 UTC, IBDesignable commented
<img width="489" alt="Снимок экрана 2023-06-19 в 09 37 04" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/483aee88-d4e4-4444-9311-babf752b63ef">

Со сломанным проектом могла наврать: тут после правок больше не показывает ошибок, но лучше перепроверить перед отправкой еще разок: скачать архив и открыть в отдельной папке. Красных файлов быть не должно
<img width="397" alt="Снимок экрана 2023-06-19 в 09 37 54" src="https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/121577115/557416a7-0961-47ad-80c3-22de5a0fe978">

2023-06-19 06:55 UTC, mahlenko commented
@IBDesignable Спасибо большое, не посмотрел, возможно получилось, что проект сломан. Просто все уже было смержено, когда разъяснили порядок сдачи. Спасибо, за подсказку про xcodeproj, при мерже столкнулись с этим))) Таким же способом и решали. Пройдусь еще раз по коду перед сдачей.