Feature/1 profile
mahlenko/iOS-FakeNFT-StarterProject-Public pull request #3
Opened 2023-06-03 20:32 UTC by DemidenGo

Profile epic

2023-06-03 20:41 UTC, DemidenGo commented
https://trello.com/b/5CFGRhC1/дипломный-проект-ios-nft

2023-06-05 10:13 UTC, ABashkirova requested changes
К сожалению, не смогла посмотреть что происходит на экранах с коллекциями из-за ошибок или недоделок – я не смогла определить по коду. Выглядит очень блокирующей и серьезной проблемой для меня. Нужно проверить жизненный цикл экранов (все ли делегаты доживают, до возвращения результата), правильно ли работают байдинги. В следующую сдачу это все нужно будет устранить. 

Верстку до конца оценить не могу. 


![RocketSim_Recording_iPhone_14_Pro_Max_2023-06-05_13 09 37](https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/20269264/4636caef-bb42-4ca6-9dab-d5c16da750cc)
![RocketSim_Recording_iPhone_14_Pro_Max_2023-06-05_13 09 55](https://github.com/mahlenko/iOS-FakeNFT-StarterProject-Public/assets/20269264/c7e179ab-aff7-4d18-9cef-014d6362a990)

2023-06-05 10:13 UTC, ABashkirova commented on FakeNFT/Profile/Model/NFTStore.swift
> +        nfts.forEach { nft in
Возвращаюсь к тому замечанию про делегатов и комплишены: почему они тут лучше работают. 

Когда ты передаешь замыкание, ты его "замечаешь" и ожидаешь, что оно будет вызвано по завершению работы функции. 

Здесь очень легко пропустить следующую ошибку: метод можно вызвать с пустой коллекцией - нет проверки ни здесь, ни на уровень выше (зачем вообще идти спрашивать, если уже понятно что пустой список). В итоге я не смогла посмотреть экраны с коллекцией. 

Хотелось бы здесь видеть возвращение ошибки хотя бы – а то экранчики как начали крутить пропеллеры, так и не перестают.

2023-06-05 10:13 UTC, ABashkirova commented on FakeNFT/Profile/Model/NFTStore.swift
> +                        self?.delegate?.didReceive(nftModel)
Дочитала дальше: убедилась что это нерабочее решение. У тебя на экранах используется блокировка UI активити индикаторами, чтобы было понятно что мы что-то грутим. В итоге перестанем крутить как только одну коллекцию получим (а запрашиваем то много). 

В итоге выглядит очень не консистентно: данные еще не дошли все, а мы уже перевели стейт в "уже загружено"

2023-06-06 20:18 UTC, DemidenGo commented
Александра, добрый вечер! Приложение стало неработоспособным, потому что был изменён API. Изначально лайки в профиле прилетали стрингой. Соответственно, так я и ожидал в модели профиля. Но, после изменения бека, лайки стали прилетать массивом интов и сетевой клиент просто не мог распарсить данные профиля и отображал дефолтный профиль (моё неудачное решение). Ну и Мои нфт и Избранные нфт тоже не отображались, так как данные просто не были получены. Перед отправкой на ревью я тестировал приложение и все работало. Я бы никогда не стал отправлять заведомо нерабочий вариант.

2023-06-06 20:57 UTC, DemidenGo commented on FakeNFT/Profile/Model/NFTStore.swift
> +                        self?.delegate?.didReceive(nftModel)
По поводу второго комментария: да, модельки получаем поштучно, но я изначально знаю, сколько мы должны получить моделей нфт, во вьюМодели я считаю полученные модельки и, когда, я получаю их все, то только тогда я убираю индикатор загрузки и срабатывает байндинг

2023-06-06 21:28 UTC, DemidenGo commented on FakeNFT/Profile/Model/NFTStore.swift
> +        nfts.forEach { nft in
С коллбеками действительно получилось удобнее и красивее. Спасибо! И к тому же, у меня получилось очень быстро и безболезненно отрефакторить код с делегатов на коллбеки.

2023-06-07 04:58 UTC, mp3moto commented on FakeNFT/Profile/View/MyNFTViewController.swift
> +    }
Предлагаю везде по проекту, где происходят изменения UI делать это через DispatchQueue.main.async

2023-06-07 04:58 UTC, mp3moto commented on FakeNFT/Profile/View/ProfileViewController.swift
> +        let cell: ProfileTableViewCell = tableView.dequeueReusableCell()
Предлагаю здесь и далее по проекту использовать в методе cellForRowAt оператор guard:
guard let cell = tableView.dequeueReusableCell(withIdentifier: CellClassName.reuseIdentifier, for: indexPath) as? CellClassName.reuseIdentifier else { return UITableViewCell() }

Не уверен, но мне кажется, что, эта реализация потенциально может вызвать краш.

@ABashkirova, буду признателен, если прокомментируете это замечание

2023-06-07 17:11 UTC, DemidenGo commented on FakeNFT/Profile/View/MyNFTViewController.swift
> +    }
Насколько я понимаю, по умолчанию и так все методы UIKit, связанные с интерфейсом, выполняются на главном потоке. Здесь всё выполняется на главном потоке, вроде DispatchQueue.main.async тут будет излишним

2023-06-07 17:13 UTC, DemidenGo commented on FakeNFT/Profile/View/ProfileViewController.swift
> +        let cell: ProfileTableViewCell = tableView.dequeueReusableCell()
Так здесь guard и используется, просто он спрятан в другой файл. Я тут использую предлагаемую заготовку. Посмотри в исходном проекте файл CellsReusingUtils.swift

2023-06-08 09:01 UTC, DemidenGo commented on FakeNFT/Profile/ViewModel/ProfileViewModelProtocol.swift
> +    var isProfileUpdatingNowObservable: Observable<Bool> { get }
Это сделано для того, чтобы я мог закрыть вьюмодель протоколом, иначе я не достучусь из вью до байндинга

2023-06-08 09:41 UTC, DemidenGo commented on FakeNFT/Profile/ViewModel/ProfileViewModelProtocol.swift
> +    func didChangeProfile(_ changeParameters: [String: String])
Здесь у меня логика работы такая: в словарь стрингов я собираю изменения профиля и через вьюмодель отправляю сетевому клиенту и далее на сервер, с этими стрингами я больше нигде не работаю. Мне как раз удобно, на сервер я сразу и отправляю изменения словарём стрингов. В случае успешного обновления профиля на сервере, он отвечает мне новыми данными пользователя и уже из них я обновляю профиль. Мне кажется, в данном случае енам будет излишним. Это мне надо будет во вью строки запихнуть в енам, затем прокинуть его через вьюмодель в сетевой клиент и там разобрать на строки и положить в словарь для отправки на сервер. А так у меня сразу улетает словарик)

2023-06-08 12:14 UTC, DemidenGo commented on FakeNFT/Profile/View/ProfileViewController.swift
> +    var viewModel: ProfileViewModelProtocol? = ProfileViewModel()
В изначальной заготовке проекта есть сториборд, в котором создан ТабБарКонтроллер с вложенными в табы ВьюКонтроллерами. Поэтому ПрофайлВьюКонтроллер инитится из сториборда. Поэтому здесь получилось так. Если б можно было, я бы сториборд вообще выпилил) А как добраться в инит контроллера, если он создаётся из сторниборда, я не знаю(

2023-06-08 12:51 UTC, DemidenGo commented on FakeNFT/Profile/View/ProfileViewController.swift
> +    var viewModel: ProfileViewModelProtocol? = ProfileViewModel()
Разобрался, убрал инициализацию вьюмодели в инит

2023-06-08 14:24 UTC, mahlenko commented on FakeNFT/Profile/View/MyNFTViewController.swift
> +    }
Как бы да, таблица находится в главном потоке, но в каком потоке будет выполнятся то, что написано у тебя в фигурных скобках? Я бы действительно отправил бы все в главный поток.

Так как опыта работы под iOS мало, но мне кажется лишним DispatchQueue.main не будет. По идее, если он выполняется в главном потоке и так, приложение его пропустит. То есть, это не требует каких ощутимых ресурсов, но обезопасит твой участок кода. Конечно везде и все отправлять в основной поток не нужно. Может я и ошибаюсь. Но кажется логичным.

2023-06-08 15:18 UTC, DemidenGo commented on FakeNFT/Profile/View/MyNFTViewController.swift
> +    }
В нашем проекте всё выполняется в главном потоке, за исключением запросов в сеть, там у URLSession такой API, что комплишен неявно вызывается в фоновом потоке. Вот там, при получении данных из сети, я и перехожу из фонового в главный поток. Здесь это делать не имеет смысла.

2023-06-09 21:56 UTC, closed without merging

2023-06-12 06:46 UTC, IBDesignable commented on FakeNFT/Profile/View/ProfileViewController.swift
> +        let cell: ProfileTableViewCell = tableView.dequeueReusableCell()
Молодцы, что сами разобрались!

2023-06-12 06:47 UTC, IBDesignable commented on FakeNFT/Profile/View/MyNFTViewController.swift
> +    }
Если переход на главную очередь, как говорит @DemidenGo, правда происходит перед этим дейсвтием, то второй раз здесь это делать не нужно. 

Другое дело, что гораздо удобнее с точки зрения понимания и снятия тревожности - переводить на главную очередь "во время" то есть перед моментом обновления UI